name: Python application

on:
  workflow_dispatch:
  release:
    types: [published, prereleased, released]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Package app with pyinstaller
        run: |
          pip install git+https://github.com/dooit-org/dooit-extras.git
          python -c "with open('dooit.py', 'w') as f: f.write('from dooit.__main__ import main\nmain()\n')"
          pyinstaller --clean -F dooit.py --add-data="dooit/utils/default_config.py:dooit/utils/" --add-data="dooit/ui/styles.tcss:dooit/ui/" --hidden-import=dooit_extras.formatters --hidden-import=dooit_extras.bar_widgets --hidden-import=dooit_extras.scripts

      # Setup File name
      - name: Set Binary file name on Linux and Mac
        if: matrix.os != 'windows-latest'
        run: echo "BINARY_FILE_NAME=dooit" >> $GITHUB_ENV

      - name: Set Binary file name on Windows
        if: matrix.os == 'windows-latest'
        run: Add-Content -Path $env:GITHUB_ENV -Value "BINARY_FILE_NAME=dooit.exe"

      # Setup final release file names
      - name: Set Final file name on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "FINAL_FILE_NAME=linux-dooit" >> $GITHUB_ENV

      - name: Set Final file name on MacOs
        if: matrix.os == 'macos-latest'
        run: echo "FINAL_FILE_NAME=macos-dooit" >> $GITHUB_ENV

      - name: Set Final file name on Windows
        if: matrix.os == 'windows-latest'
        run: Add-Content -Path $env:GITHUB_ENV -Value "FINAL_FILE_NAME=windows-dooit.exe"

      - name: Rename build files
        run: cp ./dist/${{ env.BINARY_FILE_NAME }} ./dist/${{ env.FINAL_FILE_NAME }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.FINAL_FILE_NAME }}
          path: ./dist/${{ env.BINARY_FILE_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/${{ env.FINAL_FILE_NAME }}
